// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDotR-YNM0cazE_XvdBDK79GplK12IySOs',
    appId: '1:400652156863:web:300a0cff3b2bc1388f2b0a',
    messagingSenderId: '400652156863',
    projectId: 'ems-flutter-82162',
    authDomain: 'ems-flutter-82162.firebaseapp.com',
    storageBucket: 'ems-flutter-82162.appspot.com',
    measurementId: 'G-5DSSK5H0RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx3K9khm-6yCCcbVZdUIGGRXX-W-dYhuo',
    appId: '1:400652156863:android:b269844896c1c9e58f2b0a',
    messagingSenderId: '400652156863',
    projectId: 'ems-flutter-82162',
    storageBucket: 'ems-flutter-82162.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB75-_2t0MoZ3_IsenzeBR69nIbXXw6wuQ',
    appId: '1:400652156863:ios:1c3bcbf72d5564968f2b0a',
    messagingSenderId: '400652156863',
    projectId: 'ems-flutter-82162',
    storageBucket: 'ems-flutter-82162.appspot.com',
    iosClientId: '400652156863-pv8m2pfa8kjhehhnj8bihp1d4sl98dlq.apps.googleusercontent.com',
    iosBundleId: 'com.abhishekchoksi.employeeManagementSystem',
  );
}
